# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: refs/types.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'refs/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10refs/types.proto\x12\x0eneo.fs.v2.refs\"\x80\x01\n\x07\x41\x64\x64ress\x12>\n\x0c\x63ontainer_id\x18\x01 \x01(\x0b\x32\x1b.neo.fs.v2.refs.ContainerIDR\x0b\x63ontainerID\x12\x35\n\tobject_id\x18\x02 \x01(\x0b\x32\x18.neo.fs.v2.refs.ObjectIDR\x08objectID\" \n\x08ObjectID\x12\x14\n\x05value\x18\x01 \x01(\x0cR\x05value\"#\n\x0b\x43ontainerID\x12\x14\n\x05value\x18\x01 \x01(\x0cR\x05value\"\x1f\n\x07OwnerID\x12\x14\n\x05value\x18\x01 \x01(\x0cR\x05value\" \n\x08SubnetID\x12\x14\n\x05value\x18\x01 \x01(\x07R\x05value\"5\n\x07Version\x12\x14\n\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n\x05minor\x18\x02 \x01(\rR\x05minor\"o\n\tSignature\x12\x10\n\x03key\x18\x01 \x01(\x0cR\x03key\x12\x17\n\x04sign\x18\x02 \x01(\x0cR\tsignature\x12\x37\n\x06scheme\x18\x03 \x01(\x0e\x32\x1f.neo.fs.v2.refs.SignatureSchemeR\x06scheme\"=\n\x10SignatureRFC6979\x12\x10\n\x03key\x18\x01 \x01(\x0cR\x03key\x12\x17\n\x04sign\x18\x02 \x01(\x0cR\tsignature\"N\n\x08\x43hecksum\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\x1c.neo.fs.v2.refs.ChecksumTypeR\x04type\x12\x10\n\x03sum\x18\x02 \x01(\x0cR\x03sum*n\n\x0fSignatureScheme\x12\x10\n\x0c\x45\x43\x44SA_SHA512\x10\x00\x12\x18\n\x14\x45\x43\x44SA_RFC6979_SHA256\x10\x01\x12\'\n#ECDSA_RFC6979_SHA256_WALLET_CONNECT\x10\x02\x12\x06\n\x02N3\x10\x03*A\n\x0c\x43hecksumType\x12\x1d\n\x19\x43HECKSUM_TYPE_UNSPECIFIED\x10\x00\x12\x06\n\x02TZ\x10\x01\x12\n\n\x06SHA256\x10\x02\x42IZ,github.com/nspcc-dev/neofs-sdk-go/proto/refs\xaa\x02\x18Neo.FileStorage.API.Refsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'refs.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/nspcc-dev/neofs-sdk-go/proto/refs\252\002\030Neo.FileStorage.API.Refs'
  _globals['_SIGNATURESCHEME']._serialized_start=616
  _globals['_SIGNATURESCHEME']._serialized_end=726
  _globals['_CHECKSUMTYPE']._serialized_start=728
  _globals['_CHECKSUMTYPE']._serialized_end=793
  _globals['_ADDRESS']._serialized_start=37
  _globals['_ADDRESS']._serialized_end=165
  _globals['_OBJECTID']._serialized_start=167
  _globals['_OBJECTID']._serialized_end=199
  _globals['_CONTAINERID']._serialized_start=201
  _globals['_CONTAINERID']._serialized_end=236
  _globals['_OWNERID']._serialized_start=238
  _globals['_OWNERID']._serialized_end=269
  _globals['_SUBNETID']._serialized_start=271
  _globals['_SUBNETID']._serialized_end=303
  _globals['_VERSION']._serialized_start=305
  _globals['_VERSION']._serialized_end=358
  _globals['_SIGNATURE']._serialized_start=360
  _globals['_SIGNATURE']._serialized_end=471
  _globals['_SIGNATURERFC6979']._serialized_start=473
  _globals['_SIGNATURERFC6979']._serialized_end=534
  _globals['_CHECKSUM']._serialized_start=536
  _globals['_CHECKSUM']._serialized_end=614
# @@protoc_insertion_point(module_scope)
