# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: status/types.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'status/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12status/types.proto\x12\x10neo.fs.v2.status\"~\n\x06Status\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x30\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32\x1f.neo.fs.v2.status.Status.Detail\x1a#\n\x06\x44\x65tail\x12\n\n\x02id\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x0c*z\n\x07Section\x12\x13\n\x0fSECTION_SUCCESS\x10\x00\x12\x1a\n\x16SECTION_FAILURE_COMMON\x10\x01\x12\x12\n\x0eSECTION_OBJECT\x10\x02\x12\x15\n\x11SECTION_CONTAINER\x10\x03\x12\x13\n\x0fSECTION_SESSION\x10\x04*!\n\x07Success\x12\x06\n\x02OK\x10\x00\x12\x0e\n\nINCOMPLETE\x10\x01*\x8a\x01\n\nCommonFail\x12\x0c\n\x08INTERNAL\x10\x00\x12\x16\n\x12WRONG_MAGIC_NUMBER\x10\x01\x12\x1f\n\x1bSIGNATURE_VERIFICATION_FAIL\x10\x02\x12\x1a\n\x16NODE_UNDER_MAINTENANCE\x10\x03\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x04\x12\x08\n\x04\x42USY\x10\x05*\x9c\x01\n\x06Object\x12\x11\n\rACCESS_DENIED\x10\x00\x12\x14\n\x10OBJECT_NOT_FOUND\x10\x01\x12\n\n\x06LOCKED\x10\x02\x12\x1b\n\x17LOCK_NON_REGULAR_OBJECT\x10\x03\x12\x1a\n\x16OBJECT_ALREADY_REMOVED\x10\x04\x12\x10\n\x0cOUT_OF_RANGE\x10\x05\x12\x12\n\x0eQUOTA_EXCEEDED\x10\x06*k\n\tContainer\x12\x17\n\x13\x43ONTAINER_NOT_FOUND\x10\x00\x12\x12\n\x0e\x45\x41\x43L_NOT_FOUND\x10\x01\x12\x14\n\x10\x43ONTAINER_LOCKED\x10\x02\x12\x1b\n\x17\x43ONTAINER_AWAIT_TIMEOUT\x10\x03*1\n\x07Session\x12\x13\n\x0fTOKEN_NOT_FOUND\x10\x00\x12\x11\n\rTOKEN_EXPIRED\x10\x01\x42MZ.github.com/nspcc-dev/neofs-sdk-go/proto/status\xaa\x02\x1aNeo.FileStorage.API.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/nspcc-dev/neofs-sdk-go/proto/status\252\002\032Neo.FileStorage.API.Status'
  _globals['_SECTION']._serialized_start=168
  _globals['_SECTION']._serialized_end=290
  _globals['_SUCCESS']._serialized_start=292
  _globals['_SUCCESS']._serialized_end=325
  _globals['_COMMONFAIL']._serialized_start=328
  _globals['_COMMONFAIL']._serialized_end=466
  _globals['_OBJECT']._serialized_start=469
  _globals['_OBJECT']._serialized_end=625
  _globals['_CONTAINER']._serialized_start=627
  _globals['_CONTAINER']._serialized_end=734
  _globals['_SESSION']._serialized_start=736
  _globals['_SESSION']._serialized_end=785
  _globals['_STATUS']._serialized_start=40
  _globals['_STATUS']._serialized_end=166
  _globals['_STATUS_DETAIL']._serialized_start=131
  _globals['_STATUS_DETAIL']._serialized_end=166
# @@protoc_insertion_point(module_scope)
