# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: session/service.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'session/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from helpers.protobuf.refs import types_pb2 as refs_dot_types__pb2
from helpers.protobuf.session import types_pb2 as session_dot_types__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15session/service.proto\x12\x11neo.fs.v2.session\x1a\x10refs/types.proto\x1a\x13session/types.proto\"\x8b\x02\n\rCreateRequest\x12\x33\n\x04\x62ody\x18\x01 \x01(\x0b\x32%.neo.fs.v2.session.CreateRequest.Body\x12\x39\n\x0bmeta_header\x18\x02 \x01(\x0b\x32$.neo.fs.v2.session.RequestMetaHeader\x12\x43\n\rverify_header\x18\x03 \x01(\x0b\x32,.neo.fs.v2.session.RequestVerificationHeader\x1a\x45\n\x04\x42ody\x12)\n\x08owner_id\x18\x01 \x01(\x0b\x32\x17.neo.fs.v2.refs.OwnerID\x12\x12\n\nexpiration\x18\x02 \x01(\x04\"\xf1\x01\n\x0e\x43reateResponse\x12\x34\n\x04\x62ody\x18\x01 \x01(\x0b\x32&.neo.fs.v2.session.CreateResponse.Body\x12:\n\x0bmeta_header\x18\x02 \x01(\x0b\x32%.neo.fs.v2.session.ResponseMetaHeader\x12\x44\n\rverify_header\x18\x03 \x01(\x0b\x32-.neo.fs.v2.session.ResponseVerificationHeader\x1a\'\n\x04\x42ody\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x13\n\x0bsession_key\x18\x02 \x01(\x0c\x32_\n\x0eSessionService\x12M\n\x06\x43reate\x12 .neo.fs.v2.session.CreateRequest\x1a!.neo.fs.v2.session.CreateResponseBOZ/github.com/nspcc-dev/neofs-sdk-go/proto/session\xaa\x02\x1bNeo.FileStorage.API.Sessionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'session.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/nspcc-dev/neofs-sdk-go/proto/session\252\002\033Neo.FileStorage.API.Session'
  _globals['_CREATEREQUEST']._serialized_start=84
  _globals['_CREATEREQUEST']._serialized_end=351
  _globals['_CREATEREQUEST_BODY']._serialized_start=282
  _globals['_CREATEREQUEST_BODY']._serialized_end=351
  _globals['_CREATERESPONSE']._serialized_start=354
  _globals['_CREATERESPONSE']._serialized_end=595
  _globals['_CREATERESPONSE_BODY']._serialized_start=556
  _globals['_CREATERESPONSE_BODY']._serialized_end=595
  _globals['_SESSIONSERVICE']._serialized_start=597
  _globals['_SESSIONSERVICE']._serialized_end=692
# @@protoc_insertion_point(module_scope)
